import type { DiagnosisResult, InvestigationResultResponse } from "@/types/investigation";
import { formatAgentType } from "@/lib/platform";

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim()}\n`;
}

function bulletList(items: string[]): string {
  if (items.length === 0) {
    return "_None_";
  }
  return items.map((item) => `- ${item}`).join("\n");
}

function diagnosisMarkdown(diagnosis: DiagnosisResult): string {
  const parts: string[] = [];
  parts.push(section("Root Cause", diagnosis.root_cause || "_Not available_"));
  parts.push(section("Summary", diagnosis.summary || "_Not available_"));
  parts.push(
    section(
      "Confidence",
      `${diagnosis.confidence_score}% — ${diagnosis.confidence_reason || "n/a"}`,
    ),
  );

  if (diagnosis.evidence?.length) {
    parts.push(
      section(
        "Evidence",
        diagnosis.evidence
          .map((item) => `- **${item.source}:** ${item.detail}`)
          .join("\n"),
      ),
    );
  }

  parts.push(section("Suggested Fix", diagnosis.suggested_fix || "_Not available_"));

  if (diagnosis.kubectl_commands?.length) {
    parts.push(
      section(
        "Commands",
        diagnosis.kubectl_commands.map((cmd) => `\`\`\`\n${cmd}\n\`\`\``).join("\n\n"),
      ),
    );
  }

  if (diagnosis.validation_steps?.length) {
    parts.push(section("Validation Steps", bulletList(diagnosis.validation_steps)));
  }

  if (diagnosis.prevention_recommendation) {
    parts.push(section("Prevention", diagnosis.prevention_recommendation));
  }

  if (diagnosis.llm_error) {
    parts.push(section("AI Provider Error", diagnosis.llm_error));
  }

  if (diagnosis.additional_data_needed?.length) {
    parts.push(section("Next Checks", bulletList(diagnosis.additional_data_needed)));
  }

  return parts.join("\n");
}

export function buildInvestigationMarkdown(
  result: InvestigationResultResponse,
  options?: { scopeLabel?: string | null },
): string {
  const diagnosis =
    result.diagnosis ??
    result.result?.diagnosis ??
    result.aws_result?.diagnosis ??
    result.cloud_cost_result?.diagnosis ??
    null;

  const agent = formatAgentType(result.agent_type);
  const scope = options?.scopeLabel ?? "—";
  const lines: string[] = [
    `# Investigation Report`,
    ``,
    `- **ID:** \`${result.id}\``,
    `- **Agent:** ${agent}`,
    `- **Scope:** ${scope}`,
    `- **Status:** ${result.status}`,
    diagnosis?.llm_provider ? `- **AI Provider:** ${diagnosis.llm_provider}` : null,
    ``,
  ].filter((line): line is string => line !== null);

  if (diagnosis) {
    lines.push(diagnosisMarkdown(diagnosis));
  } else {
    lines.push(section("Diagnosis", "_No AI diagnosis available for this investigation._"));
  }

  if (result.error) {
    lines.push(section("Job Error", result.error));
  }

  lines.push(`---\n_Generated by DevOps Open Agent_`);
  return lines.join("\n");
}

export function downloadInvestigationMarkdown(
  result: InvestigationResultResponse,
  options?: { scopeLabel?: string | null },
): void {
  const markdown = buildInvestigationMarkdown(result, options);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `investigation-${result.id.slice(0, 8)}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function buildPrintableHtml(
  result: InvestigationResultResponse,
  options?: { scopeLabel?: string | null },
): string {
  const markdown = buildInvestigationMarkdown(result, options);
  const escaped = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Investigation ${result.id}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, sans-serif; color: #0f172a; margin: 2rem; line-height: 1.5; }
    pre { white-space: pre-wrap; word-break: break-word; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; }
    @media print {
      body { margin: 0.75in; }
    }
  </style>
</head>
<body>
  <pre>${escaped}</pre>
</body>
</html>`;
}

/**
 * Open the system print dialog (Save as PDF) via a same-origin blob iframe.
 * Avoids blank about:blank popups caused by window.open(..., "noopener").
 */
export function printInvestigationPdf(
  result: InvestigationResultResponse,
  options?: { scopeLabel?: string | null },
): void {
  if (typeof window === "undefined" || typeof document === "undefined") {
    return;
  }

  const html = buildPrintableHtml(result, options);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const iframe = document.createElement("iframe");
  iframe.setAttribute("title", "Print investigation report");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  iframe.src = url;
  document.body.appendChild(iframe);

  const cleanup = () => {
    window.setTimeout(() => {
      iframe.remove();
      URL.revokeObjectURL(url);
    }, 1000);
  };

  iframe.onload = () => {
    try {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } finally {
      cleanup();
    }
  };
}
